name: Deploy to GCP Bucket

on:
  push:
    branches:
      - master
      - ci/*

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: npm install, build
        run: |
          npm install
          npm run build
#         env:
#           CI: true

      - name: Authenticate to GCP
        uses: actions/gcloud/auth@master
        env:
          GCLOUD_AUTH: ${{ secrets.GCP_SA_KEY }}

      - name: Upload to GCP bucket
        uses: docker://gcr.io/cloud-builders/gsutil
        with:
          args: -m rsync -d -r ./build gs://${{ secrets.BUCKET_URI }}/
        env:
          CLOUDSDK_CORE_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}


      - name: Make files publicly accessible
        uses: docker://gcr.io/cloud-builders/gsutil
        with:
          args: -m acl ch -r -u AllUsers:R gs://${{ secrets.BUCKET_URI }}/*
        env:
          CLOUDSDK_CORE_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}


      - name: Edit the bucket configuration 
        uses: docker://gcr.io/cloud-builders/gsutil
        with:
          args: web set -m index.html -e index.html gs://${{ secrets.BUCKET_URI }}
        env:
          CLOUDSDK_CORE_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
