name: Deploy to GCP Bucket

on:
  push:
    branches:
      - master
      - ci/*

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: npm install, build
        run: |
          npm install
          npm run build
#         env:
#           CI: true

      - name: Print
        run: |
          pwd
          ls -al
          cd build
          ls -al

#       - name: Authenticate to GCP
#         uses: actions/gcloud/auth@master
#         env:
#           GCLOUD_AUTH: ${{ secrets.GCP_SA_KEY }}

#       - name: Push to GCP Bucket
#         uses: actions/gcloud/cli@master
#         with:
#           args: "components install beta --quiet && gcloud beta run deploy ${{ secrets.GCLOUD_APP_NAME }} --quiet --image gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }} --region us-east1 --project ${{ secrets.GCLOUD_PROJECT }} --platform managed"

#       - name: Upload to GCP bucket
#         uses: docker://gcr.io/cloud-builders/gsutil
#         with:
#           args: -m cp -r build/* < bucket link for gsutil >
#         env:
#           CLOUDSDK_CORE_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
